# {{ project_name }}

Generated by Tempify.

- Author: {{ author }}
- License: {{ license }}
- Namespace: {{ namespace }}

{{ if include_ci }}
- CI: {{ ci_provider }}
{{ else }}
- CI: disabled
{{ endif }}

{{ if docs_url }}
- Docs: {{ docs_url }}
{{ endif }}

## Build

```bash
cmake -S . -B build
cmake --build build
```
